export const authCopy = {
  signIn: {
    title: "Entrar no JobIn",
    subtitle: "Enviaremos um código de acesso ao seu e-mail para você",
    emailLabel: "E-mail",
    emailPlaceholder: "voce@email.com",
    submit: "Continuar",
    submitting: "Enviando...",
    invalidEmail: "Digite um e-mail válido para receber o código.",
    genericError: "Não foi possível enviar o código. Tente novamente.",
    legal: {
      prefix: "Ao continuar você concorda com os ",
      terms: "Termos de uso",
      middle: " e a ",
      privacy: "Política de privacidade",
      suffix: ".",
    },
  },
  verify: {
    title: "Confirme seu código",
    subtitlePrefix: "Enviamos 6 dígitos para ",
    subtitleSuffix: ".",
    submit: "Verificar",
    submitting: "Confirmando...",
    resend: "Reenviar código",
    resendIn: (seconds: number) => `Reenviar código em ${seconds}s`,
    resent: "Código reenviado.",
    invalidCode: "Código inválido ou expirado. Tente de novo.",
    genericError: "Não foi possível confirmar o código. Tente novamente.",
  },
};
